### ISSUE TITLE
persistent meteors

### ISSUE THREAD

**Issue by durandom** [AICoE/meteor-operator#42]
As a User of the Meteor Web Site,
I want to check a box,
so that a deployed meteor is not garbage collected
and so that the URLs can be shared

**Acceptance Criteria**
- [ ] checkbox to request "persistent" is visible on UI

Some alternatives:
* make the timeout configurable (24hr, 1w, never)
* add CNAME routing for nice URLs
* add deployed meteor to a catalog.metor.zone website
* make the timeout and URL changes after the meteor is deployed

**Comment by tumido** [comment]
Resolved via https://github.com/AICoE/meteor-operator/pull/49 working on deployment to prod in few next days
