### ISSUE TITLE
Meteor enabled for private repos

### ISSUE THREAD

**Issue by hemajv** [AICoE/meteor-operator#51]
Is it possible to use meteor for rendering a jupyterbook from private repos? I would like to use meteor for this repo: https://github.com/AICoE/okr. The repo aims to have OKR reporting notebooks for the team that we would like to render as a hosted jupyterbook.

**Comment by hemajv** [comment]
cc @durandom

**Comment by tumido** [comment]
I think this should be possible through sesheta/AICoE GitHub application and it's tokens within the pipelines, correct @harshad16 @goern ?

Though I'm afraid meteor won't be able to easily do the same on the Shower frontend where it tries to dynamically populate the branches for each repo.. I think in that case we can fall back to text input in the UI.

**Comment by goern** [comment]
Do we consider "build from private repository" a high priority feature of Meteor? Do we have an RFE issue for this? Is this a feature separating between "use a pipeline to continuously deployt of a notebook repo" (aicoe-ci/cd) and "build some notebooks on-demand" (meteor)

@durandom 

/kind feature
/label needs-triage

**Comment by durandom** [comment]
@HumairAK can you elaborate how the build process for a jupyterbook works with the apps repository? Maybe we don't need meteor for this usecase...

**Comment by durandom** [comment]
@hemajv check out https://github.blog/changelog/2021-01-21-access-control-for-github-pages/ and https://github.com/operate-first/apps/blob/master/.github/workflows/book.yml 
Let's just not use meteor for the OKR repo :)

**Comment by hemajv** [comment]
> @hemajv check out https://github.blog/changelog/2021-01-21-access-control-for-github-pages/ and https://github.com/operate-first/apps/blob/master/.github/workflows/book.yml Let's just not use meteor for the OKR repo :)

seems like we need to have GitHub Pro to enable https://github.blog/changelog/2021-01-21-access-control-for-github-pages/ :confused: 

will look into https://github.com/operate-first/apps/blob/master/.github/workflows/book.yml instead

**Comment by tumido** [comment]
One thing to consider here though is that: Once you build a private repository, you're effectively making it public - the JupyterBook is exposed to public and anybody can spawn the JupyterHub image. Do we want that?

**Comment by HumairAK** [comment]
@durandom it uses github actions, which is configured as you pointed out [here](https://github.com/operate-first/apps/blob/master/.github/workflows/book.yml). This allows a build to be initiated everytime a change is pushed to the /docs path.

**Comment by hemajv** [comment]
> @durandom it uses github actions, which is configured as you pointed out [here](https://github.com/operate-first/apps/blob/master/.github/workflows/book.yml). This allows a build to be initiated everytime a change is pushed to the /docs path.

Tried out the github actions to trigger a  jupyter book build, the build was created successfully, however a URL will still not be generated as gh-pages is disabled for private repos. We can pull the gh-pages branch to view the jupyter book locally.
